name: Build develop
on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths-ignore:
      - '.github/**'

jobs:
  build:
    name: "Build and push Docker image"
    runs-on: ubuntu-latest

    steps:
      - name : "Checkout Action"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🕹️ Git Version
        id: version
        uses: codacy/git-version@2.8.0
        with:
          minor-identifier: 'feat:'
          dev-branch: ${{ github.ref_name }}

      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.4.0

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          push: true
          build-args: |
            ENV=dev
          tags: ${{ secrets.REGISTRY_USERNAME }}/${{ github.event.repository.name }}:${{ steps.version.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Trigger CD
        uses: peter-evans/repository-dispatch@v2.1.1
        with:
          event-type: deploy-develop
          repository: valentin-barbotin/esgi-devops-gitops
          token: ${{ secrets.PAT }}
          client-payload: '
            {
              "service": "${{ github.event.repository.name }}",
              "version": "${{ steps.version.outputs.version }}"
            }
            '