name: Tests
on:
  workflow_dispatch:
  pull_request_target:
    branches:
      - develop
      - master
      - release/*
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '.github/**'

jobs:
  build:
    name: "Build image and run tests"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Action"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: "Set up Docker Buildx"
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: "First Stage"
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          load: true
          tags: ${{ secrets.REGISTRY_USERNAME }}/${{ github.event.repository.name }}:pr-${{ github.event.number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            ENV=ci
          target: builder

      - name: Tests
        run: |
          docker run --network=host --env-file=.env.ci --rm ${{ secrets.REGISTRY_USERNAME }}/${{ github.event.repository.name }}:pr-${{ github.event.number }} pnpm test
